#!/usr/bin/env bash

# Template thanks to William Melody.
# See https://github.com/alphabetum/bash-boilerplate for more info.

set -o nounset
set -o errexit
set -o pipefail

DEFAULT_IFS="$IFS"
SAFER_IFS=$'\n\t'
IFS="$SAFER_IFS"

# Set to the program's basename.
_ME="${0##*/}"

_print_help() {
  cat << 'EOF'
Compute how much you owe to whom based on the data
located in the 'debts.csv' file.

Usage:
  $_ME [<arguments>]
  $_ME -h | --help

Options:
  -v --verbose  Show details.
  -h --help  Show this screen.
EOF
}

_compute_debts() {
  tail -n +2 debts.csv | awk -f debts.awk -v verbose="$1"
}

_main() {
  # Avoid complex option parsing when only one program option is expected.
  if [[ "${1:-}" =~ ^-h|--help$  ]]; then
    _print_help
  elif [[ "${1:-}" =~ ^-v|--verbose ]]; then
    _compute_debts 'y'
  else
    _compute_debts 'n'
  fi
}

# Call `_main` after everything has been defined.
_main "${@:-}"
